apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-dp
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube-container
        image: sonarqube
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 900Mi
          requests:
            cpu: 250m
            memory: 500Mi
