apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-dp
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube-container
        image: sonarqube
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 900Mi
          requests:
            cpu: 250m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-svc
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-balancer
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
  type: LoadBalancer
  ports:
    - port: 9000
      nodePort: 9000